### ISSUE TITLE
Game crashes after load (actually after subscribing to additional assets)

### ISSUE THREAD

**Issue by fizyk** [keallu/CSL-ResizeIt#2]
@keallu I've been crashing with the issue for a bit, and I've been debugging it on the paradox forum: https://forum.paradoxplaza.com/forum/threads/cities-skylines-steam-game-crashes-after-load.1527655/

The first time it occurred I subscribed to additional assets. Unsubscribing fixed the issue initially, however, I also had missing assets, which subscribing again, fixed the issue. Surprisingly, clearing vehicles on load also was fixing the issue.

**Comment by keallu** [comment]
I have not been able to reproduce issue. Closing.
